### PR TITLE
Decrypt in parallel using rayon

### PR DESCRIPTION
**Pull request by mortendahl**
This might actually hurt performance so should be benched before merging.

### CODE REVIEW

**Comment by mortendahl** [comment]
Would like to do a bit of benching first. Is it blocking?

**Comment by mortendahl** [comment]
In sequence:
```
test self::bench_decryption<KeySize2048>      ... bench:   3,531,093 ns/iter (+/- 116,137)
test self::bench_decryption<KeySize4096>      ... bench:  27,917,733 ns/iter (+/- 6,986,494)
```

In parallel:
```
test self::bench_decryption<KeySize2048>      ... bench:   1,886,814 ns/iter (+/- 302,931)
test self::bench_decryption<KeySize4096>      ... bench:  14,045,181 ns/iter (+/- 3,400,457)
```

**Comment by mortendahl** [comment]
@gbenattar @omershlo can you think of any reason why people wouldn't want to do decryption in parallel, i.e. is there a need to put this under a (default?) feature flag? Wondering if there could be any security concerns?

**Comment by omershlo** [comment]
I think that it's ok (but I would like to think more about it) as long as:
1. We provide the user only one method to decrypt (the user can't compare parallel and serial decryprion times)
2. p and q are on the same size.

This parallel decryption is a major win for performance!

**Comment by mortendahl** [comment]
any new thoughts on this @omershlo (re https://github.com/mortendahl/rust-paillier/pull/13#issuecomment-399740277)?

**Comment by omershlo** [comment]
nope :) . let's do it

**Pull request merged**
